### ISSUE TITLE
docker-compose.yml example

### ISSUE THREAD

**Issue by noeRls** [ajacobson/chiadog-docker#6]
Hi,
That would be great to have a `docker-compose.yml` file example.

**Comment by ajacobson** [comment]
I'd be happy to accept a pull request with an example 🙂

I don't have experience using compose (yet).

**Comment by noeRls** [comment]
Here is an example:
```yaml
version: "3"

services:
    chia-dod:
        container_name: chia-dog
        image: artjacobson/chiadog-docker:latest
        volumes:
            - ./config:/root/.chiadog
            - /path/to/chia/log:/root/.chia/mainnet/log:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
```
